export const fieldMapping = [
  {
    name: "payerEntityName",
    label: "Payer Entity Name",
    type: "text",
    requiredAtStep: [1, 2, 4],
    group: "payer",
  },
  {
    name: "payerEntityAbn",
    label: "Payer Entity ABN",
    type: "number",
    requiredAtStep: [1, 2, 4],
    group: "payer",
  },
  {
    name: "payerEntityAcnArbn",
    label: "Payer Entity ACN/ARBN",
    type: "number",
    requiredAtStep: [1, 2, 4],
    group: "payer",
  },
  {
    name: "payeeEntityName",
    label: "Payee Entity Name",
    type: "text",
    requiredAtStep: [1, 2, 4],
    group: "payee",
  },
  {
    name: "payeeEntityAbn",
    label: "Payee Entity ABN",
    type: "number",
    requiredAtStep: [1, 2, 4],
    group: "payee",
  },
  {
    name: "payeeEntityAcnArbn",
    label: "Payee Entity ACN/ARBN",
    type: "number",
    requiredAtStep: [1, 2, 4],
    group: "payee",
  },
  {
    name: "paymentAmount",
    label: "Payment Amount",
    type: "amount",
    requiredAtStep: [1, 2, 4],
    group: "payment",
  },
  {
    name: "description",
    label: "Description",
    type: "text",
    requiredAtStep: [1, 2, 4],
    group: "payment",
  },
  {
    name: "transactionType",
    label: "Transaction Type",
    type: "text",
    requiredAtStep: [1, 2, 4],
    group: "payment",
  },
  {
    name: "supplyDate",
    label: "Supply Date",
    type: "text",
    requiredAtStep: [1, 2, 4],
    group: "payment",
  },
  {
    name: "paymentDate",
    label: "Payment Date",
    type: "date",
    requiredAtStep: [1, 2, 4],
    group: "payment",
  },
  {
    name: "contractPoReferenceNumber",
    label: "Contract/PO Reference Number",
    type: "text",
    requiredAtStep: [1, 2, 4],
    group: "contract",
  },
  {
    name: "contractPoPaymentTerms",
    label: "Contract/PO Payment Terms",
    type: "number",
    requiredAtStep: [1, 2, 4],
    group: "contract",
  },
  {
    name: "noticeForPaymentIssueDate",
    label: "Notice for Payment Issue Date",
    type: "text",
    requiredAtStep: [1, 2, 4],
    group: "notice",
  },
  {
    name: "noticeForPaymentTerms",
    label: "Notice for Payment Terms",
    type: "text",
    requiredAtStep: [1, 2, 4],
    group: "notice",
  },
  {
    name: "invoiceReferenceNumber",
    label: "Invoice Reference Number",
    type: "text",
    requiredAtStep: [1, 2, 4],
    group: "invoice",
  },
  {
    name: "invoiceIssueDate",
    label: "Invoice Issue Date",
    type: "date",
    requiredAtStep: [1, 2, 4],
    group: "invoice",
  },
  {
    name: "invoiceReceiptDate",
    label: "Invoice Receipt Date",
    type: "date",
    requiredAtStep: [1, 2, 4],
    group: "invoice",
  },
  {
    name: "invoiceAmount",
    label: "Invoice Amount",
    type: "amount",
    requiredAtStep: [1, 2, 4],
    group: "invoice",
  },
  {
    name: "invoicePaymentTerms",
    label: "Invoice Payment Terms",
    type: "text",
    requiredAtStep: [1, 2, 4],
    group: "invoice",
  },
  {
    name: "invoiceDueDate",
    label: "Invoice Due Date",
    type: "date",
    requiredAtStep: [1, 2, 4],
    group: "invoice",
  },
  {
    name: "isTcp",
    label: "Mark as TCP",
    type: "checkbox",
    requiredAtStep: [1, 2, 4],
    group: "step 1",
  },
  {
    name: "tcpExclusionComment",
    label: "Exclusion Reason",
    type: "text",
    requiredAtStep: [1, 2, 4],
    group: "step 1",
  },
  {
    name: "peppolEnabled",
    label: "Peppol eInvoice Enabled",
    type: "checkbox",
    requiredAtStep: [2, 4],
    group: "step 2",
  },
  {
    name: "rcti",
    label: "RCTI",
    type: "checkbox",
    requiredAtStep: [2, 4],
    group: "step 2",
  },
  {
    name: "creditCardPayment",
    label: "Credit Card Payment",
    type: "checkbox",
    requiredAtStep: [2, 4],
    group: "step 2",
  },
  {
    name: "creditCardNumber",
    label: "Credit Card Number",
    type: "text",
    requiredAtStep: [2, 4],
    group: "step 2",
  },
  {
    name: "partialPayment",
    label: "Partial Payment",
    type: "checkbox",
    requiredAtStep: [4],
    group: "step 4",
  },
  {
    name: "paymentTerm",
    label: "Payment Term",
    type: "text",
    requiredAtStep: [2, 4],
    group: "step 2",
  },
  {
    name: "excludedTcp",
    label: "Excluded TCP",
    type: "checkbox",
    requiredAtStep: [1, 2, 4],
    group: "step 2",
  },
  {
    name: "explanatoryComments1",
    label: "Explanatory Comments",
    type: "textArea",
    requiredAtStep: [2, 4],
    group: "step 2",
  },
  {
    name: "isSb",
    label: "Small Business",
    type: "checkbox",
    requiredAtStep: [2, 4],
    group: "step 4",
  },
  {
    name: "paymentTime",
    label: "Payment Time (days)",
    type: "number",
    requiredAtStep: [4],
    group: "step 4",
  },
  {
    name: "explanatoryComments2",
    label: "Explanatory Comments",
    type: "textArea",
    requiredAtStep: [2, 4],
    group: "step 4",
  },
];
