version: 2
updates:
  # NPM / Node.js dependencies (MAIN ONLY)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "deps"

  # GitHub Actions dependencies (MAIN ONLY)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps"
