// src/features/pulse/maximiser/ui/IntroductionPanel.jsx
import { Box, Stack, TextField, Typography, Divider } from "@mui/material";

export default function IntroductionPanel({ value, onChange }) {
  const text = value?.text ?? "";
  return (
    <Box>
      <Typography variant="h6">Introduction</Typography>
      <Divider sx={{ my: 1 }} />
      <Stack spacing={2}>
        <TextField
          label="Introduction (rich text allowed later)"
          value={text}
          onChange={(e) => onChange?.({ text: e.target.value })}
          multiline
          minRows={6}
          placeholder="The snapshot report provides a clear, data-driven view of team performance. Insights are generated by ingesting timesheet data into Pulse and applying AI analysis to detect patterns across activity, capacity, and delivery trends. The outcome is not simply a retrospective of hours worked, but an intelligence layer that highlights strengths, surfaces risks, and points to opportunities for improvement. These insights are powered by Pulse Maximiser — the AI-driven analytics engine that transforms raw timesheet data into clear, actionable intelligence.
Leaders can use the report to quickly understand where delivery is accelerating, where planning processes are holding firm, and where bottlenecks or risks are emerging. It is designed as an executive-level brief: fast to digest, but sufficiently detailed that any reader can grasp the context and act with confidence.
"
          fullWidth
        />
      </Stack>
    </Box>
  );
}
