// src/features/pulse/maximiser/MaximiserStudio.js
import { Grid, Paper, Stack, Box, Button, Typography } from "@mui/material";
import { useTheme } from "@mui/material/styles";
import { useEffect, useMemo, useState, useCallback, useRef } from "react";
import { useAlert } from "../../../context/";
import { parseTimesheetsCsv, aggregateForPdf } from "./timesheet_adapter";
import {
  downloadPulseInsightsPdf,
  getPulseInsightsPdfBlobUrl,
  revokePdfBlobUrl,
} from "./maximiser_script";

import CoverPanel from "./ui/CoverPanel";
import PrimersPanel from "./ui/PrimersPanel";
import BulletsPanel from "./ui/BulletsPanel";
import AboutCtaPanel from "./ui/AboutCtaPanel";
import DataPanel from "./ui/DataPanel";
import PreviewExportBar from "./ui/PreviewExportBar";
import ThemePanel from "./ui/ThemePanel";
import ExecutiveSummaryPanel from "./ui/ExecutiveSummaryPanel";
import { pulseService } from "../../../services/pulse/pulse";

export default function MaximiserStudio() {
  const t = useTheme();
  const { showAlert } = useAlert();

  // Seed with sensible defaults so export works immediately
  const [state, setState] = useState({
    cover: {
      title: "Pulse Team Performance Insights",
      subtitle:
        "From spreadsheets to clarity. AI-driven analysis of team timesheets for executive insight.",
      chips: {
        sector: "",
        audience: "",
        horizon: "",
      },
      watermarkSample: false,
    },
    introduction: {
      text:
        "The snapshot report provides a clear, data-driven view of team performance. " +
        "Insights are generated by ingesting timesheet data into Pulse and " +
        "applying AI analysis to detect patterns across activity, capacity, and delivery trends. " +
        "The outcome is not simply a retrospective of hours worked, " +
        "but an intelligence layer that highlights strengths, surfaces risks, and points to opportunities for improvement. " +
        "The insights are powered by Pulse Maximiser — the AI-driven analytics engine that " +
        "transforms raw timesheet data into clear, actionable intelligence." +
        "\n\n" +
        "Leaders can use this report to quickly understand where delivery is accelerating, " +
        "where planning processes are holding firm, and where bottlenecks or risks are emerging. " +
        "It is designed as an executive-level brief: fast to digest, " +
        "but sufficiently detailed that any reader can grasp the context and act with confidence.",
    },
    primers: {
      sector: "",
      audience: "",
      priorities: [""],
      successMetrics: [""],
      constraints: [""],
      timeHorizon: "",
      notes: "",
      purpose:
        "The primers establish the context in which this snapshot should be read and interpreted. They summarise scope, intended audience, drivers and constraints so findings are understood in the right frame.",
    },
    execSummary: { auto: true, bullets: [] },
    highlights: {
      enabled: true,
      bullets: [""],
    },
    attention: {
      enabled: true,
      bullets: [""],
    },
    urgent: {
      enabled: true,
      bullets: [""],
    },
    about: {
      paragraphs: [
        "Pulse replaces the reliance on static spreadsheets with a single, intelligent source of truth for engagements, resources, and budgets. " +
          "By combining real-time utilisation data with AI-driven analysis, it gives leaders immediate visibility into what is working well and where intervention is required.",
        "Key features include: " +
          "\n\n• Real-time utilisation and planning accuracy — monitor capacity and demand continuously rather than waiting for periodic reports. " +
          "\n• AI-generated summaries and risk signals — automated analysis surfaces the issues that matter most, reducing noise and highlighting actionable insights." +
          "\n• Streamlined timesheets and engagement visibility — data capture is simplified, making it easier for teams to provide accurate inputs while leaders gain clearer oversight." +
          "\n\nPulse is designed to help professional services organisations and project-based teams move from firefighting with outdated data to making confident, proactive decisions.",
      ],
      cta: "From spreadsheets to clarity. Join Pulse for a live view of your team’s reality — and the next best action.",
      registrationUrl: "https://www.monochrome-compliance.com/pulse/join",
    },
    data: { rows: [], aggregates: null },
    themeOverrides: {}, // <-- for ThemePanel
    insights: { good: [], attention: [], urgent: [] },
  });

  const [previewUrl, setPreviewUrl] = useState(null);
  const [isPreviewing, setIsPreviewing] = useState(false);
  const previewUrlRef = useRef(null);

  useEffect(() => {
    return () => {
      if (previewUrlRef.current) revokePdfBlobUrl(previewUrlRef.current);
    };
  }, []);

  useEffect(() => {
    if (previewUrlRef.current && previewUrlRef.current !== previewUrl) {
      revokePdfBlobUrl(previewUrlRef.current);
    }
    previewUrlRef.current = previewUrl;
  }, [previewUrl]);

  const set = (key) => (val) => setState((s) => ({ ...s, [key]: val }));

  const pdfTheme = useMemo(() => {
    const base = {
      mode: t.palette.mode,
      primary: t.palette.primary.main,
      secondary: t.palette.secondary.main,
      textPrimary: t.palette.text.primary,
      textSecondary: t.palette.text.secondary,
      bgPaper: t.palette.background.paper,
      brandBand: t.palette.primary.main,
      legendGrey: t.palette.mode === "light" ? "#666666" : "#bbbbbb",
      grid: t.palette.mode === "light" ? "#e6e8eb" : "#3a3a4d",
    };
    return { ...base, ...state.themeOverrides }; // <-- merge overrides
  }, [t, state.themeOverrides]);

  const {
    cover,
    primers,
    execSummary,
    introduction,
    about,
    data,
    insights,
    highlights,
    attention,
    urgent,
  } = state;
  const aggregates = data?.aggregates;

  // Lightweight tagging so each bullet can map to a chart on the PDF
  const tagInsight = useCallback((text) => {
    const s = String(text || "").toLowerCase();
    if (
      s.includes("throughput") ||
      s.includes("velocity") ||
      s.includes("trend")
    )
      return { tag: "throughput" };
    if (s.includes("on-time") || s.includes("on time"))
      return { tag: "onTime", payload: { label: "On-time start" } };
    if (s.includes("qa")) return { tag: "qa", payload: { label: "QA pass" } };
    if (s.includes("variance") || s.includes("mape") || s.includes("estimate"))
      return { tag: "variance" };
    return { tag: "score" };
  }, []);

  const insightsFromPanels = useCallback(
    (s) => {
      const toList = (grp) =>
        Array.isArray(grp?.bullets)
          ? grp.bullets.filter((t) => !!t && String(t).trim() !== "")
          : [];
      const goodList = toList(s.highlights);
      const attnList = toList(s.attention);
      const urgList = toList(s.urgent);

      const hasManual = goodList.length || attnList.length || urgList.length;
      if (!hasManual)
        return s.insights || { good: [], attention: [], urgent: [] };

      const map = (arr) =>
        arr.map((t) => ({ text: String(t), ...tagInsight(t) }));

      return {
        good: map(goodList),
        attention: map(attnList),
        urgent: map(urgList),
      };
    },
    [tagInsight]
  );

  const refreshPreview = useCallback(
    async (overrides = {}) => {
      setIsPreviewing(true);
      try {
        const insightsForPdf = insightsFromPanels({
          highlights,
          attention,
          urgent,
          insights,
        });
        const url = await getPulseInsightsPdfBlobUrl({
          cover,
          primer: primers,
          execSummary,
          introduction: introduction?.text || "",
          about,
          data: overrides.dataAggregates ?? aggregates,
          brand: { product: "Pulse", company: "Monochrome Compliance" },
          registrationUrl: about?.registrationUrl,
          theme: pdfTheme,
          insights: insightsForPdf,
        });
        setPreviewUrl(url);
      } catch (e) {
        console.error(e);
        showAlert("Preview failed.", "error");
      } finally {
        setIsPreviewing(false);
      }
    },
    [
      insightsFromPanels,
      highlights,
      attention,
      urgent,
      insights,
      cover,
      primers,
      execSummary,
      introduction?.text,
      about,
      aggregates,
      pdfTheme,
      showAlert,
    ]
  );

  useEffect(() => {
    const hasInsights = !!(
      insights?.good?.length ||
      insights?.attention?.length ||
      insights?.urgent?.length
    );
    if (!aggregates && !hasInsights) return;
    refreshPreview();
  }, [aggregates, insights, highlights, attention, urgent, refreshPreview]);

  // Fallback: simple FE heuristic if BE /maximiser/analyse is unavailable
  const deriveFindingsLocal = (aggregates) => {
    if (!aggregates) return { positive: [], risks: [], critical: [] };
    const {
      throughputByWeek = [],
      positiveScores = [],
      estVarianceByTeam = [],
    } = aggregates;

    // growth over last vs first 3 weeks
    const avg = (arr) =>
      arr.length ? arr.reduce((s, n) => s + Number(n || 0), 0) / arr.length : 0;
    const growthPct = (() => {
      if (!Array.isArray(throughputByWeek) || throughputByWeek.length < 6)
        return 0;
      const base = avg(throughputByWeek.slice(0, 3)) || 0;
      const last = avg(throughputByWeek.slice(-3));
      return base ? Math.round(((last - base) / base) * 100) : 0;
    })();

    const getScore = (labelPart) => {
      const l = String(labelPart).toLowerCase();
      const f = (positiveScores || []).find((p) =>
        String(p?.label || "")
          .toLowerCase()
          .includes(l)
      );
      return Number(f?.score) || 0;
    };
    const onTime = getScore("on-time");
    const qa = getScore("qa");

    const critical = [];
    if (onTime && onTime < 60)
      critical.push(`On-time start very low (~${Math.round(onTime)}%).`);
    if (qa && qa < 65)
      critical.push(`QA pass rate very low (~${Math.round(qa)}%).`);
    const extremeVar = (
      Array.isArray(estVarianceByTeam) ? estVarianceByTeam : []
    ).find((t) => Number.isFinite(t?.variance) && t.variance >= 35);
    if (extremeVar)
      critical.push(
        `Extreme variance in ${extremeVar.team} (~${Math.round(extremeVar.variance)}%).`
      );

    const risks = [];
    const lowScores = (positiveScores || [])
      .slice()
      .sort((a, b) => a.score - b.score)
      .slice(0, 2);
    for (const s of lowScores) {
      if (Number.isFinite(s?.score))
        risks.push(`${s.label} below target (~${Math.round(s.score)}%).`);
    }
    const highVarTeams = (
      Array.isArray(estVarianceByTeam) ? estVarianceByTeam : []
    )
      .filter((t) => Number.isFinite(t?.variance) && t.variance >= 15)
      .sort((a, b) => b.variance - a.variance)
      .slice(0, 3)
      .map((t) => `${t.team} (~${t.variance}%)`);
    if (highVarTeams.length)
      risks.push(
        `High estimation variance observed in ${highVarTeams.join(", ")}.`
      );

    const positive = [];
    if (growthPct > 0)
      positive.push(`Delivery velocity trending up ~${growthPct}%.`);
    const topPos = (positiveScores || [])
      .slice()
      .sort((a, b) => b.score - a.score)[0];
    if (topPos && Number.isFinite(topPos.score)) {
      positive.push(`${topPos.label} strong (~${Math.round(topPos.score)}%).`);
    }

    const uniq = (arr) => Array.from(new Set((arr || []).filter(Boolean)));
    return {
      positive: uniq(positive),
      risks: uniq(risks),
      critical: uniq(critical),
    };
  };

  const onUpload = async (file) => {
    try {
      const rows = await parseTimesheetsCsv(file);
      const aggregates = aggregateForPdf(rows);

      // Prepare payload for BE analyse (Option B)
      const payload = {
        throughputByWeek: aggregates?.throughputByWeek || [],
        positiveScores: aggregates?.positiveScores || [],
        estVarianceByTeam: aggregates?.estVarianceByTeam || [],
        estimationLabels: aggregates?.estimationLabels || [],
        estimationPlanned: aggregates?.estimationPlanned || [],
        estimationActual: aggregates?.estimationActual || [],
      };

      let findings;
      try {
        findings = await pulseService.maximiser.analyse(payload);
      } catch (err) {
        console.warn(
          "[Maximiser] analyse endpoint failed; using local findings fallback",
          err
        );
        findings = deriveFindingsLocal(aggregates);
      }

      const nextAggregates = {
        ...aggregates,
        urgent: Array.isArray(findings?.critical) ? findings.critical : [],
      };

      // Derive structured insights
      const structured = {
        good: (findings?.positive || []).map((t) => ({
          text: t,
          ...tagInsight(t),
        })),
        attention: (findings?.risks || []).map((t) => ({
          text: t,
          ...tagInsight(t),
        })),
        urgent: (findings?.critical || []).map((t) => ({
          text: t,
          ...tagInsight(t),
        })),
      };

      setState((s) => ({
        ...s,
        data: { rows, aggregates: nextAggregates },
        // Map findings to the three panels so the user can edit, and seed insights
        highlights: {
          ...s.highlights,
          bullets: (structured.good || []).map((i) => i.text),
        },
        attention: {
          ...s.attention,
          bullets: (structured.attention || []).map((i) => i.text),
        },
        urgent: {
          ...s.urgent,
          bullets: (structured.urgent || []).map((i) => i.text),
        },
        insights: structured,
        // Executive Summary: switch to manual with AI findings
        execSummary: {
          auto: false,
          bulletsByGroup: {
            positive: findings?.positive || [],
            risks: findings?.risks || [],
            critical: findings?.critical || [],
          },
          nextSteps: findings?.nextSteps || "",
        },
      }));

      showAlert("Timesheets parsed and analysed. Preview updating…", "success");
      await refreshPreview({ dataAggregates: nextAggregates });
    } catch (e) {
      console.error(e);
      showAlert("Failed to parse/analyse timesheets.", "error");
    }
  };

  const onExport = async () => {
    const insightsForPdf = insightsFromPanels(state);
    try {
      await downloadPulseInsightsPdf({
        cover: state.cover,
        primer: state.primers,
        execSummary: state.execSummary,
        introduction: state.introduction?.text || "",
        about: state.about,
        data: state.data?.aggregates,
        brand: { product: "Pulse", company: "Monochrome Compliance" },
        registrationUrl: state.about?.registrationUrl,
        theme: pdfTheme,
        insights: insightsForPdf,
      });
      showAlert("PDF generated.", "success");
    } catch (e) {
      console.error(e);
      showAlert("Export failed.", "error");
    }
  };

  return (
    <Grid container spacing={2}>
      <Grid item xs={12} md={6} lg={5}>
        <Stack spacing={2}>
          <Paper sx={{ p: 2 }}>
            <DataPanel onUpload={onUpload} />
          </Paper>
          <Paper sx={{ p: 2 }}>
            <CoverPanel value={state.cover} onChange={set("cover")} />
          </Paper>
          <Paper sx={{ p: 2 }}>
            <PrimersPanel value={state.primers} onChange={set("primers")} />
          </Paper>
          <Paper sx={{ p: 2 }}>
            <ExecutiveSummaryPanel
              value={state.execSummary}
              onChange={set("execSummary")}
            />
          </Paper>
          <Paper sx={{ p: 2 }}>
            <BulletsPanel
              title="What’s Going Well"
              value={state.highlights}
              onChange={set("highlights")}
              colorHint={t.palette.success.main}
            />
          </Paper>
          <Paper sx={{ p: 2 }}>
            <BulletsPanel
              title="Areas for Attention"
              value={state.attention}
              onChange={set("attention")}
              colorHint={t.palette.warning.main}
            />
          </Paper>
          <Paper sx={{ p: 2 }}>
            <BulletsPanel
              title="Urgent Focus"
              value={state.urgent}
              onChange={set("urgent")}
              colorHint={t.palette.error.main}
            />
          </Paper>
          <Paper sx={{ p: 2 }}>
            <AboutCtaPanel value={state.about} onChange={set("about")} />
          </Paper>
          <Paper sx={{ p: 2 }}>
            <ThemePanel
              value={state.themeOverrides}
              onChange={set("themeOverrides")}
            />
          </Paper>
          <PreviewExportBar onExport={onExport} />
        </Stack>
      </Grid>

      <Grid item xs={12} md={6} lg={7}>
        <Paper
          sx={{
            p: 2,
            minHeight: 480,
            display: "flex",
            flexDirection: "column",
            gap: 1,
          }}
        >
          <Box
            sx={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <Typography variant="h6">Preview (A4)</Typography>
            <Box sx={{ display: "flex", gap: 1 }}>
              <Button
                variant="outlined"
                onClick={refreshPreview}
                disabled={isPreviewing}
              >
                {isPreviewing ? "Rendering…" : "Refresh Preview"}
              </Button>
              <Button variant="contained" onClick={onExport}>
                Export PDF
              </Button>
            </Box>
          </Box>

          <Box
            sx={{
              flex: 1,
              border: "1px solid",
              borderColor: "divider",
              borderRadius: 1,
              overflow: "auto",
            }}
          >
            {previewUrl ? (
              <iframe
                title="Pulse PDF Preview"
                src={previewUrl}
                style={{ width: "100%", height: "100vh", border: 0 }}
              />
            ) : (
              <Box
                sx={{
                  height: "100%",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                <Typography variant="body2" color="text.secondary">
                  Click “Refresh Preview” to render the latest PDF
                </Typography>
              </Box>
            )}
          </Box>
        </Paper>
      </Grid>
    </Grid>
  );
}
